<h1 class="legacy">Coronavirus: why is eastern Europe's second wave so much worse than its first?</h1>


<span><a href="https://theconversation.com/profiles/tamara-popic-1179735">Tamara Popic</a>, <em><a href="https://theconversation.com/institutions/european-university-institute-1363">European University Institute</a></em> and <a href="https://theconversation.com/profiles/alexandru-d-moise-1179360">Alexandru D Moise</a>, <em><a href="https://theconversation.com/institutions/european-university-institute-1363">European University Institute</a></em></span>

<p>Eastern Europe was praised for being exceptional during the first wave of the pandemic. By introducing very strict <a href="https://www.ft.com/content/f9850a8d-7323-4de5-93ed-9ecda7f6de1c">prevention measures</a> early on, countries in the region had <a href="https://www.theguardian.com/world/2020/may/05/why-has-eastern-europe-suffered-less-from-coronavirus-than-the-west">significantly fewer</a> COVID-related deaths than their western European counterparts.</p>

<p>Some argued that this was because of <a href="https://www.economist.com/europe/2020/05/28/eastern-europes-covid-19-recession-could-match-its-post-communist-one">economics</a>: that eastern European countries locked down early because they feared their economies would not be able to handle many people getting sick. Others suggested this eastern European exceptionalism could be explained by <a href="https://kafkadesk.org/2020/09/18/what-people-got-wrong-about-the-covid-19-pandemic-in-central-and-eastern-europe/">culture</a>, with success in limiting the first wave being down to a mentality of fear and readiness to follow harsh rules stemming from the communist era.</p>

<p>But if these factors were at play in the first wave, they haven’t had the same effect in the second. Eastern Europe’s pandemic experience has been dramatically different this autumn. All countries in the region have seen significant increases in <a href="https://ourworldindata.org/coronavirus-data-explorer?zoomToSelection=true&amp;time=2020-03-01..latest&amp;country=SVN%7EHUN%7EHRV%7ESRB%7EBGR%7ECZE%7EROU%7EPOL%7ELVA%7EEST%7ELTU%7ESVK&amp;region=World&amp;casesMetric=true&amp;interval=smoothed&amp;perCapita=true&amp;smoothing=7&amp;pickerMetric=new_deaths_per_million&amp;pickerSort=desc">cases</a> and <a href="https://ourworldindata.org/coronavirus-data-explorer?zoomToSelection=true&amp;time=2020-03-01..latest&amp;country=SVN%7EHUN%7EHRV%7ESRB%7EBGR%7ECZE%7EROU%7EPOL%7ELVA%7EEST%7ELTU%7ESVK&amp;region=World&amp;deathsMetric=true&amp;interval=smoothed&amp;perCapita=true&amp;smoothing=7&amp;pickerMetric=new_deaths_per_million&amp;pickerSort=desc">deaths</a>. Here, we take a look at why this has happened.</p>

<h2>A head start in the first wave</h2>

<p>One thing is clear: eastern Europe exited the first wave at the end of June in much better shape than western Europe. Adjusting for population size, both cases and deaths were substantially lower in the east, as shown in this comparison of the COVID-19 death rate in the two regions. </p>

<figure class="align-center zoomable">
            <a href="https://images.theconversation.com/files/371763/original/file-20201127-19-1ym7gaf.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=1000&amp;fit=clip"><img alt="Graph showing that during March-June 2020, COVID-19 deaths per head of population spiked in western Europe but remained low in eastern Europe." src="https://images.theconversation.com/files/371763/original/file-20201127-19-1ym7gaf.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=754&amp;fit=clip" srcset="https://images.theconversation.com/files/371763/original/file-20201127-19-1ym7gaf.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=600&amp;h=269&amp;fit=crop&amp;dpr=1 600w, https://images.theconversation.com/files/371763/original/file-20201127-19-1ym7gaf.png?ixlib=rb-1.1.0&amp;q=30&amp;auto=format&amp;w=600&amp;h=269&amp;fit=crop&amp;dpr=2 1200w, https://images.theconversation.com/files/371763/original/file-20201127-19-1ym7gaf.png?ixlib=rb-1.1.0&amp;q=15&amp;auto=format&amp;w=600&amp;h=269&amp;fit=crop&amp;dpr=3 1800w, https://images.theconversation.com/files/371763/original/file-20201127-19-1ym7gaf.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=754&amp;h=338&amp;fit=crop&amp;dpr=1 754w, https://images.theconversation.com/files/371763/original/file-20201127-19-1ym7gaf.png?ixlib=rb-1.1.0&amp;q=30&amp;auto=format&amp;w=754&amp;h=338&amp;fit=crop&amp;dpr=2 1508w, https://images.theconversation.com/files/371763/original/file-20201127-19-1ym7gaf.png?ixlib=rb-1.1.0&amp;q=15&amp;auto=format&amp;w=754&amp;h=338&amp;fit=crop&amp;dpr=3 2262w" sizes="(min-width: 1466px) 754px, (max-width: 599px) 100vw, (min-width: 600px) 600px, 237px"></a>
            <figcaption>
              <span class="caption">Daily new COVID-19 deaths per million inhabitants, eastern and western Europe.</span>
              <span class="attribution"><span class="source">Our World in Data COVID-19 Dataset. Authors’ compilation.</span></span>
            </figcaption>
          </figure>

<p>We can also compare how restrictive the two regions’ disease-prevention measures were during the first wave using the <a href="https://www.bsg.ox.ac.uk/research/research-projects/coronavirus-government-response-tracker">Oxford COVID-19 government response tracker</a> (OxCGRT). This tool measures the stringency of efforts to control the virus on a scale of 0-100, with 100 being the most restrictive. We can see from the next graph that, at the same time in the spring, the two regions introduced measures that were similarly strict. </p>

<p>However, if we look back at the death rates of the two regions in the graph above, it’s clear that eastern European countries introduced restrictions when experiencing far fewer cases and deaths. Therefore, the simplest explanation for why eastern Europe initially fared much better is that it had a head start. Countries in the region imposed strict measures while being relatively mildly affected, whereas western countries waited until things got bad. </p>

<figure class="align-center zoomable">
            <a href="https://images.theconversation.com/files/371764/original/file-20201127-17-1v0ue6h.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=1000&amp;fit=clip"><img alt="Graph showing how eastern Europe's COVID-19 control measures were initially as stringent as western Europe's, but since the summer have been more relaxed." src="https://images.theconversation.com/files/371764/original/file-20201127-17-1v0ue6h.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=754&amp;fit=clip" srcset="https://images.theconversation.com/files/371764/original/file-20201127-17-1v0ue6h.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=600&amp;h=257&amp;fit=crop&amp;dpr=1 600w, https://images.theconversation.com/files/371764/original/file-20201127-17-1v0ue6h.png?ixlib=rb-1.1.0&amp;q=30&amp;auto=format&amp;w=600&amp;h=257&amp;fit=crop&amp;dpr=2 1200w, https://images.theconversation.com/files/371764/original/file-20201127-17-1v0ue6h.png?ixlib=rb-1.1.0&amp;q=15&amp;auto=format&amp;w=600&amp;h=257&amp;fit=crop&amp;dpr=3 1800w, https://images.theconversation.com/files/371764/original/file-20201127-17-1v0ue6h.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=754&amp;h=323&amp;fit=crop&amp;dpr=1 754w, https://images.theconversation.com/files/371764/original/file-20201127-17-1v0ue6h.png?ixlib=rb-1.1.0&amp;q=30&amp;auto=format&amp;w=754&amp;h=323&amp;fit=crop&amp;dpr=2 1508w, https://images.theconversation.com/files/371764/original/file-20201127-17-1v0ue6h.png?ixlib=rb-1.1.0&amp;q=15&amp;auto=format&amp;w=754&amp;h=323&amp;fit=crop&amp;dpr=3 2262w" sizes="(min-width: 1466px) 754px, (max-width: 599px) 100vw, (min-width: 600px) 600px, 237px"></a>
            <figcaption>
              <span class="caption">Stringency of COVID-19 control measures in eastern and western Europe.</span>
              <span class="attribution"><span class="source">OxCGRT. Authors’ compilation.</span></span>
            </figcaption>
          </figure>

<p>This shows that eastern European countries took the opportunity to act quickly.</p>

<h2>Squandering the spring gains</h2>

<p>When we turn to the second wave (starting around September and ongoing), we’re faced with the opposite question: why did eastern European countries not act in spite of rapidly rising infections and deaths?</p>

<p>Eastern European death rates overtook those in the west in early October, but restrictions in the region – which had eased after the first wave – still lagged behind controls reintroduced in the west. Look again at the second graph above. It shows that in between the two waves, the east relaxed its measures further than the west, and was then less eager in reimposing them. Eastern Europe squandered its spring gains and then repeated the mistakes made by the west in spring: waiting until cases and deaths are out of control before imposing controls.</p>

<p>What explains this reluctance to reintroduce restrictions? One explanation might be that these countries are victims of their own success. Eastern Europe contained the virus so successfully in spring, it didn’t experience the <a href="https://www.bmj.com/content/368/bmj.m1065">horrific hospital scenes</a> seen in northern Italy, for example. This may have produced <a href="https://www.politico.eu/article/as-infections-grow-in-romania-so-does-corona-scepticism/">scepticism</a> about the severity of the pandemic. <a href="https://www.bbc.co.uk/news/health-54417547">Pandemic fatigue</a> is present across the entire continent, and may be especially present in the <a href="https://apnews.com/article/virus-outbreak-pandemics-bucharest-romania-archive-2998096f7aa9161099d8e0e42c018177">east</a>, where some people may have felt that they went into a lockdown for nothing.</p>

<h2>Not all in the same boat</h2>

<p>Importantly, however, there have been major differences within eastern Europe too. Up until the beginning of November, the spike in the death rate was largely driven by the Czech Republic. Cases and deaths have not been spread evenly across the region.</p>

<figure class="align-center zoomable">
            <a href="https://images.theconversation.com/files/371765/original/file-20201127-13-yjtbs4.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=1000&amp;fit=clip"><img alt="Graph showing COVID deaths per head of population in eastern European countries from September 15 to November 1, with the Czech Republic faring significantly worse than others." src="https://images.theconversation.com/files/371765/original/file-20201127-13-yjtbs4.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=754&amp;fit=clip" srcset="https://images.theconversation.com/files/371765/original/file-20201127-13-yjtbs4.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=600&amp;h=259&amp;fit=crop&amp;dpr=1 600w, https://images.theconversation.com/files/371765/original/file-20201127-13-yjtbs4.png?ixlib=rb-1.1.0&amp;q=30&amp;auto=format&amp;w=600&amp;h=259&amp;fit=crop&amp;dpr=2 1200w, https://images.theconversation.com/files/371765/original/file-20201127-13-yjtbs4.png?ixlib=rb-1.1.0&amp;q=15&amp;auto=format&amp;w=600&amp;h=259&amp;fit=crop&amp;dpr=3 1800w, https://images.theconversation.com/files/371765/original/file-20201127-13-yjtbs4.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=754&amp;h=326&amp;fit=crop&amp;dpr=1 754w, https://images.theconversation.com/files/371765/original/file-20201127-13-yjtbs4.png?ixlib=rb-1.1.0&amp;q=30&amp;auto=format&amp;w=754&amp;h=326&amp;fit=crop&amp;dpr=2 1508w, https://images.theconversation.com/files/371765/original/file-20201127-13-yjtbs4.png?ixlib=rb-1.1.0&amp;q=15&amp;auto=format&amp;w=754&amp;h=326&amp;fit=crop&amp;dpr=3 2262w" sizes="(min-width: 1466px) 754px, (max-width: 599px) 100vw, (min-width: 600px) 600px, 237px"></a>
            <figcaption>
              <span class="caption">Daily new COVID-19 deaths per million inhabitants, second wave, eastern Europe.</span>
              <span class="attribution"><span class="source">Our World in Data COVID-19 Dataset. Authors’ compilation.</span></span>
            </figcaption>
          </figure>

<p>If we look at the stringency of control measures, we can also see that not all countries acted in the same way. The Czech Republic acted very late, for example, imposing stricter measures at the end of October, even though cases and deaths had been soaring upwards during the month. Neighbouring Slovakia, on the other hand, imposed stricter measures despite having far fewer cases and deaths. It seems that at least some countries in the region have learned their lessons.</p>

<figure class="align-center zoomable">
            <a href="https://images.theconversation.com/files/371766/original/file-20201127-24-14r6rz6.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=1000&amp;fit=clip"><img alt="Graph showing how the stringency of some eastern European countries' COVID-19 control measures increased between September 15 and November 1." src="https://images.theconversation.com/files/371766/original/file-20201127-24-14r6rz6.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=754&amp;fit=clip" srcset="https://images.theconversation.com/files/371766/original/file-20201127-24-14r6rz6.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=600&amp;h=261&amp;fit=crop&amp;dpr=1 600w, https://images.theconversation.com/files/371766/original/file-20201127-24-14r6rz6.png?ixlib=rb-1.1.0&amp;q=30&amp;auto=format&amp;w=600&amp;h=261&amp;fit=crop&amp;dpr=2 1200w, https://images.theconversation.com/files/371766/original/file-20201127-24-14r6rz6.png?ixlib=rb-1.1.0&amp;q=15&amp;auto=format&amp;w=600&amp;h=261&amp;fit=crop&amp;dpr=3 1800w, https://images.theconversation.com/files/371766/original/file-20201127-24-14r6rz6.png?ixlib=rb-1.1.0&amp;q=45&amp;auto=format&amp;w=754&amp;h=328&amp;fit=crop&amp;dpr=1 754w, https://images.theconversation.com/files/371766/original/file-20201127-24-14r6rz6.png?ixlib=rb-1.1.0&amp;q=30&amp;auto=format&amp;w=754&amp;h=328&amp;fit=crop&amp;dpr=2 1508w, https://images.theconversation.com/files/371766/original/file-20201127-24-14r6rz6.png?ixlib=rb-1.1.0&amp;q=15&amp;auto=format&amp;w=754&amp;h=328&amp;fit=crop&amp;dpr=3 2262w" sizes="(min-width: 1466px) 754px, (max-width: 599px) 100vw, (min-width: 600px) 600px, 237px"></a>
            <figcaption>
              <span class="caption">Stringency of COVID-19 restrictions, second wave, eastern Europe.</span>
              <span class="attribution"><span class="source">OxCGRT. Authors’ compilation.</span></span>
            </figcaption>
          </figure>

<p>Understanding why eastern European countries chose to respond differently during the second wave is complicated, though. </p>

<p>For example, differences in economic strength could explain why the relatively richer Czech Republic waited to reintroduce restrictions (thinking it could bear the brunt of a high number of infections), but this doesn’t account for the relatively poorer Romania’s decision to do the same. </p>

<p>Politics might provide a hint: the <a href="https://theconversation.com/coronavirus-what-went-wrong-in-the-czech-republic-149505">Czech Republic</a> held regional elections in October, while Romania voted in local elections in September and is about to vote in <a href="https://www.romania-insider.com/general-elections-campaign-romania-2020">national elections</a> in December. Electoral politics could explain the reluctance of the two countries to enter another lockdown – with politicians seeing it as an unpopular measure that would also delay elections.</p>

<p>But one explanation that can probably be ditched is the culture argument mentioned previously. Even in countries where governments reintroduced relatively strong restrictions in October, such as Slovenia and Lithuania, infections and deaths have <a href="https://ourworldindata.org/coronavirus-data-explorer?zoomToSelection=true&amp;time=2020-03-01..latest&amp;country=SVN%7ELTU&amp;region=World&amp;casesMetric=true&amp;interval=smoothed&amp;perCapita=true&amp;smoothing=7&amp;pickerMetric=new_deaths_per_million&amp;pickerSort=desc">remained high</a> throughout November – suggesting low compliance with the rules.<!-- Below is The Conversation's page counter tag. Please DO NOT REMOVE. --><img src="https://counter.theconversation.com/content/150430/count.gif?distributor=republish-lightbox-basic" alt="The Conversation" width="1" height="1" style="border: none !important; box-shadow: none !important; margin: 0 !important; max-height: 1px !important; max-width: 1px !important; min-height: 1px !important; min-width: 1px !important; opacity: 0 !important; outline: none !important; padding: 0 !important; text-shadow: none !important" /><!-- End of code. If you don't see any code above, please get new code from the Advanced tab after you click the republish button. The page counter does not collect any personal data. More info: https://theconversation.com/republishing-guidelines --></p>

<p><span><a href="https://theconversation.com/profiles/tamara-popic-1179735">Tamara Popic</a>, Max Weber Fellow in Social and Political Sciences, <em><a href="https://theconversation.com/institutions/european-university-institute-1363">European University Institute</a></em> and <a href="https://theconversation.com/profiles/alexandru-d-moise-1179360">Alexandru D Moise</a>, Max Weber Fellow in Social and Political Sciences, <em><a href="https://theconversation.com/institutions/european-university-institute-1363">European University Institute</a></em></span></p>

<p>This article is republished from <a href="https://theconversation.com">The Conversation</a> under a Creative Commons license. Read the <a href="https://theconversation.com/coronavirus-why-is-eastern-europes-second-wave-so-much-worse-than-its-first-150430">original article</a>.</p>
